FROM nginx:1.17.3

ENV REDIRECT_1_PATH="/REDIRECT_1_PATH_NOT_EXIST_XXX"
ENV REDIRECT_1_TARGET_URL="/REDIRECT_1_TARGET_URL_NOT_EXIST_XXX"
ENV REDIRECT_2_PATH="/REDIRECT_2_PATH_NOT_EXIST_XXX"
ENV REDIRECT_2_TARGET_URL="/REDIRECT_2_TARGET_URL_NOT_EXIST_XXX"
ENV REDIRECT_3_PATH="/REDIRECT_3_PATH_NOT_EXIST_XXX"
ENV REDIRECT_3_TARGET_URL="/REDIRECT_3_TARGET_URL_NOT_EXIST_XXX"
ENV REDIRECT_4_PATH="/REDIRECT_4_PATH_NOT_EXIST_XXX"
ENV REDIRECT_4_TARGET_URL="/REDIRECT_4_TARGET_URL_NOT_EXIST_XXX"
ENV REDIRECT_5_PATH="/REDIRECT_5_PATH_NOT_EXIST_XXX"
ENV REDIRECT_5_TARGET_URL="/REDIRECT_5_TARGET_URL_NOT_EXIST_XXX"

ENV PROXY_1_PATH="/PROXY_1_PATH_NOT_EXIST_XXX"
ENV PROXY_1_TARGET_URL="/PROXY_1_TARGET_URL_NOT_EXIST_XXX"
ENV PROXY_2_PATH="/PROXY_2_PATH_NOT_EXIST_XXX"
ENV PROXY_2_TARGET_URL="/PROXY_2_TARGET_URL_NOT_EXIST_XXX"
ENV PROXY_3_PATH="/PROXY_3_PATH_NOT_EXIST_XXX"
ENV PROXY_3_TARGET_URL="/PROXY_3_TARGET_URL_NOT_EXIST_XXX"
ENV PROXY_4_PATH="/PROXY_4_PATH_NOT_EXIST_XXX"
ENV PROXY_4_TARGET_URL="/PROXY_4_TARGET_URL_NOT_EXIST_XXX"
ENV PROXY_5_PATH="/PROXY_5_PATH_NOT_EXIST_XXX"
ENV PROXY_5_TARGET_URL="/PROXY_5_TARGET_URL_NOT_EXIST_XXX"

COPY nginx.tmpl /etc/nginx/conf.d/default.tmpl
CMD /bin/sh -c "envsubst < /etc/nginx/conf.d/default.tmpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
